### ISSUE TITLE
Differences between linux and windows

### ISSUE THREAD

**Issue by kosmylo** [ucuapps/modelicagym#14]
I would like to ask if I can use modelicagym for windows and whether there are any disadvantages to using windows compared to linux.

**Comment by OlehLuk** [comment]
Hi! Thanks for your interest in this tool.
1. Yes, you can use `modelocagym` toolbox on windows, as soon as you have an FMU compiled for Windows and functioning properly. I did this for my research projects successfully. The FMUs provided in this repo were compiled for Linux, that's why it was tested on Linux. 
2. You will need an FMU compiled for Windows and this is where you may face some issues. These issues are related to Modelica tool that is used for compilation (JModelica/OpenModelica/Dymola/...). Therefore, please refer to the corresponding sources to tackle them.

**Comment by kosmylo** [comment]
Awesome, thanks!
